### ISSUE TITLE
Improve deployment [EPIC]

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#389]
- [x] [Continuous deployment with Travis](https://github.com/MetaCell/geppetto-scidash/issues/392)
- [x] [Improve deployment to remove all manual steps as much as possible](https://github.com/MetaCell/geppetto-scidash/issues/393)
- [x] [Re-align readme with latest documentation](https://github.com/MetaCell/geppetto-scidash/issues/394) 
- [x] [Integrated automated testing with continuous deployment](https://github.com/MetaCell/geppetto-scidash/issues/388)
