### ISSUE TITLE
Fix python unit testing

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#414]
- [x] [Create django tests to test connection to the Java backend #412](https://github.com/MetaCell/geppetto-scidash/issues/412)
- [x] [Draft / design unit test plan](https://github.com/MetaCell/geppetto-scidash/issues/415)
- [x] [Implement unit testing](https://github.com/MetaCell/geppetto-scidash/issues/417) 
- [ ] [Fix scidash api testing and automate it](https://github.com/MetaCell/geppetto-scidash/issues/416)
